# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'documents/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='neural_network_param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_basic', models.IntegerField(null=True)),
                ('output_basic', models.IntegerField(null=True)),
                ('layers_basic', models.IntegerField(null=True)),
                ('input_complex', models.IntegerField(null=True)),
                ('output_complex', models.IntegerField(null=True)),
                ('layers_complex', models.IntegerField(null=True)),
                ('desired_error', models.FloatField(null=True)),
                ('max_epochs', models.IntegerField(null=True)),
                ('neurons_hidden1', models.IntegerField(null=True)),
                ('neurons_hidden2', models.IntegerField(null=True)),
                ('fann_set_activation_function_hidden', models.IntegerField(choices=[(0, b'FANN_LINEAR'), (1, b'FANN_THRESHOLD'), (2, b'FANN_THRESHOLD_SYMMETRIC'), (3, b'FANN_SIGMOID'), (4, b'FANN_SIGMOID_STEPWISE'), (5, b'FANN_SIGMOID_SYMMETRIC'), (6, b'FANN_SIGMOID_SYMMETRIC_STEPWISE'), (7, b'FANN_GAUSSIAN'), (8, b'FANN_GAUSSIAN_SYMMETRIC'), (9, b'FANN_GAUSSIAN_STEPWISE'), (10, b'FANN_ELLIOT'), (11, b'FANN_ELLIOT_SYMMETRIC'), (12, b'FANN_LINEAR_PIECE'), (13, b'FANN_LINEAR_PIECE_SYMMETRIC'), (14, b'FANN_SIN_SYMMETRIC'), (15, b'FANN_COS_SYMMETRIC'), (16, b'FANN_SIN'), (17, b'FANN_COS')], null=True)),
                ('fann_set_activation_function_output', models.IntegerField(choices=[(0, b'FANN_LINEAR'), (1, b'FANN_THRESHOLD'), (2, b'FANN_THRESHOLD_SYMMETRIC'), (3, b'FANN_SIGMOID'), (4, b'FANN_SIGMOID_STEPWISE'), (5, b'FANN_SIGMOID_SYMMETRIC'), (6, b'FANN_SIGMOID_SYMMETRIC_STEPWISE'), (7, b'FANN_GAUSSIAN'), (8, b'FANN_GAUSSIAN_SYMMETRIC'), (9, b'FANN_GAUSSIAN_STEPWISE'), (10, b'FANN_ELLIOT'), (11, b'FANN_ELLIOT_SYMMETRIC'), (12, b'FANN_LINEAR_PIECE'), (13, b'FANN_LINEAR_PIECE_SYMMETRIC'), (14, b'FANN_SIN_SYMMETRIC'), (15, b'FANN_COS_SYMMETRIC'), (16, b'FANN_SIN'), (17, b'FANN_COS')], null=True)),
                ('size_of_block_orientation', models.IntegerField(null=True)),
                ('size_of_block_gabor', models.IntegerField(null=True)),
                ('sigma', models.IntegerField(null=True)),
                ('var_lambda', models.IntegerField(null=True)),
                ('gamma', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'Running'), (2, b'Completed')], default=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Document')),
                ('task_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neural_network_param')),
            ],
        ),
    ]
