# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 4, 28, 20, 31, 22, 536559, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neural_network_param',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
